/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/client`
 */
// #region Functions
export declare function createRpcClient<ServerFunctions extends object = Record<string, never>, ClientFunctions extends object = Record<string, never>>(_: ClientFunctions, _: {
  channel: ChannelOptions;
  rpcOptions?: Partial<BirpcOptions<ServerFunctions, ClientFunctions, boolean>>;
}): BirpcReturn<ServerFunctions, ClientFunctions, false>;
// #endregion