/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/server`
 */
// #region Functions
export declare function createRpcServer<ClientFunctions extends object = Record<string, never>, ServerFunctions extends object = Record<string, never>>(_: ServerFunctions, _?: {
  rpcOptions?: EventOptions<ClientFunctions, ServerFunctions, false>;
}): BirpcGroup<ClientFunctions, ServerFunctions, false>;
// #endregion