/**
 * Generate `stories/Overview.mdx` from the co-located component stories on disk,
 * so the single Overview page never drifts from the story files.
 *
 * Run with `pnpm run docs:overview` (or `pnpm -C storybook docs:overview`).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { glob } from 'tinyglobby'

const here = dirname(fileURLToPath(import.meta.url))
const root = fileURLToPath(new URL('../..', import.meta.url))
const storiesDirs = [
  `${root}/packages/core/src/client/webcomponents`,
  `${root}/packages/ui/src/components`,
]
const outFile = `${here}/../stories/Overview.mdx`

interface Entry {
  importName: string
  importPath: string
  title: string
  docsId: string
  firstExport: string
}

/** Storybook's docs path id: `Dock/Group/Popover` -> `dock-group-popover`. */
function toDocsId(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

/** A safe MDX import identifier derived from the story title. */
function toImportName(title: string): string {
  const pascal = title.replace(/[^a-z0-9]+/gi, ' ').trim().split(/\s+/).map(w => w[0]!.toUpperCase() + w.slice(1)).join('')
  return `S${pascal}`
}

const files = (await Promise.all(
  storiesDirs.map(dir => glob('**/*.stories.ts', { cwd: dir, absolute: true })),
)).flat().sort()

const entries: Entry[] = []
for (const file of files) {
  const src = await readFile(file, 'utf-8')
  // Scope to the `meta` block so we don't pick up a fixture's `title:` field.
  const title = src.match(/const meta\s*=\s*\{[\s\S]*?title:\s*['"]([^'"]+)['"]/)?.[1]
  if (!title)
    continue
  const firstExport = src.match(/export const (\w+)\s*:/)?.[1]
  if (!firstExport)
    continue
  const importPath = relative(dirname(outFile), file).replace(/\.ts$/, '')
  entries.push({
    importName: toImportName(title),
    importPath,
    title,
    docsId: toDocsId(title),
    firstExport,
  })
}

const imports = entries.map(e => `import * as ${e.importName} from '${e.importPath}'`).join('\n')
const sections = entries.map(e =>
  `### [${e.title}](/?path=/docs/${e.docsId}--docs)\n\n<Canvas of={${e.importName}.${e.firstExport}} />`,
).join('\n\n')

const content = `{/* AUTO-GENERATED by scripts/gen-overview.mts — run \`pnpm run docs:overview\` to refresh. */}

import { Canvas, Meta } from '@storybook/addon-docs/blocks'
${imports}

<Meta title="Overview" />

# Vite DevTools — Client Components

A gallery of the dock and floating-panel components that make up the embedded
and standalone DevTools client. Each heading links to that component's own docs
page; use the theme toggle in the toolbar to preview light and dark.

${sections}
`

await mkdir(dirname(outFile), { recursive: true })
await writeFile(outFile, content, 'utf-8')

console.log(`Wrote ${relative(root, outFile)} (${entries.length} components)`)
