/**
 * Generated by tsnapi — public API snapshot of `devframe/node/auth`
 */
// #region Interfaces
export interface PendingAuthRequest {
  clientAuthToken: string;
  session: DevToolsNodeRpcSession;
  ua: string;
  origin: string;
  resolve: (_: {
    isTrusted: boolean;
  }) => void;
  abortController: AbortController;
  timeout: ReturnType<typeof setTimeout>;
}
// #endregion

// #region Functions
export declare function abortPendingAuth(): void;
export declare function consumeTempAuthToken(_: string, _: SharedState<InternalAnonymousAuthStorage>): string | null;
export declare function getPendingAuth(): PendingAuthRequest | null;
export declare function getTempAuthToken(): string;
export declare function refreshTempAuthToken(): string;
export declare function revokeActiveConnectionsForToken(_: DevToolsNodeContext, _: string): Promise<void>;
export declare function revokeAuthToken(_: DevToolsNodeContext, _: SharedState<InternalAnonymousAuthStorage>, _: string): Promise<void>;
export declare function setPendingAuth(_: PendingAuthRequest | null): void;
// #endregion