/**
 * Generated by tsnapi — public API snapshot of `devframe/node/internal`
 */
// #region Functions
export declare function normalizeBasePath(_: string): string;
export declare function resolveBasePath(_: DevframeDefinition, _: DevframeDeploymentKind): string;
// #endregion

// #region Other
export { DevToolsInternalContext }
export { getInternalContext }
export { InternalAnonymousAuthStorage }
export { internalContextMap }
export { RemoteTokenRecord }
// #endregion