ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - langium

packages:
  - packages/*
  - docs

catalogs:
  build:
    '@antfu/ni': ^28.2.0
    '@nuxt/kit': ^4.2.2
    '@nuxt/vite-builder': https://pkg.pr.new/@nuxt/vite-builder@33682
    '@unocss/nuxt': ^66.6.0
    '@vitejs/plugin-vue': ^6.0.3
    '@vueuse/nuxt': ^14.1.0
    esbuild: ^0.27.2
    magic-string: ^0.30.21
    nitropack: ^2.13.1
    nuxt: ^4.2.2
    rolldown: ^1.0.0-rc.2
    tsdown: ^0.20.1
    tsx: ^4.21.0
    turbo: ^2.7.6
    unocss: ^66.6.0
    unplugin-vue: ^7.1.1
    vite: ^8.0.0-beta.10
  deps:
    '@pnpm/read-project-manifest': ^1001.2.4
    '@rolldown/debug': ^1.0.0-rc.2
    ansis: ^4.2.0
    birpc: ^4.0.0
    birpc-x: 0.0.6
    cac: ^6.7.14
    diff: ^8.0.3
    get-port-please: ^3.2.0
    h3: ^1.15.5
    immer: ^11.1.3
    launch-editor: ^2.12.0
    mlly: ^1.8.0
    mrmime: ^2.0.1
    obug: ^2.1.1
    ohash: ^2.0.11
    open: ^11.0.0
    p-limit: ^7.2.0
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    publint: ^0.3.17
    sirv: ^3.0.2
    split2: ^4.2.0
    structured-clone-es: ^1.0.0
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    unconfig: ^7.4.2
    unstorage: ^1.17.4
    webext-bridge: ^6.0.1
    ws: ^8.19.0
  devtools:
    '@antfu/eslint-config': ^7.2.0
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.13.0
    '@typescript-eslint/utils': ^8.54.0
    '@unocss/eslint-config': ^66.6.0
    bumpp: ^10.4.0
    chokidar: ^5.0.0
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
    vite-plugin-inspect: ^11.3.3
    vue-tsc: ^3.2.4
  docs:
    '@shikijs/vitepress-twoslash': ^3.21.0
    '@voidzero-dev/vitepress-theme': ^4.4.1
    mermaid: ^11.12.2
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.7.1
    vitepress-plugin-mermaid: ^2.0.17
  frontend:
    '@floating-ui/dom': ^1.7.5
    '@vueuse/components': ^14.1.0
    '@vueuse/core': ^14.1.0
    '@vueuse/router': ^14.1.0
    '@xterm/addon-fit': ^0.11.0
    '@xterm/xterm': ^6.0.0
    codemirror: ^5.65.20
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    diff-match-patch-es: ^1.0.1
    dompurify: ^3.3.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    my-ua-parser: ^2.0.4
    nanovis: ^1.0.0
    splitpanes: ^4.0.4
    theme-vitesse: ^1.0.0
    vite-hot-client: ^2.1.0
    vue: ^3.5.27
    vue-virtual-scroller: ^2.0.0-beta.8
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/codicon': ^1.2.41
    '@iconify-json/fluent': ^1.2.37
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/octicon': ^1.2.20
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.7
    '@iconify-json/simple-icons': ^1.2.68
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/tabler': ^1.2.26
  inlined:
    '@antfu/utils': ^9.3.0
    '@clack/prompts': ^0.11.0
    stream-json: ^1.9.1
  playground:
    unplugin-vue-router: ^0.19.2
    vite-plugin-vue-tracer: ^1.2.0
    vue-router: ^4.6.4
  resolutions:
    '@jridgewell/sourcemap-codec': 1.5.0
    langium: ^4.2.0
    semver: ^7.7.3
  testing:
    vitest: ^4.0.18
    vitest-package-exports: ^1.1.2
    yaml: ^2.8.2
  types:
    '@types/chrome': ^0.1.36
    '@types/codemirror': ^5.60.17
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/diff': ^8.0.0
    '@types/split2': ^4.2.3
    '@types/splitpanes': ^2.2.6
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
