packages:
  - packages/*
  - docs

shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
ignoreWorkspaceRootCheck: true

catalogs:
  build:
    '@antfu/ni': ^27.0.1
    '@nuxt/kit': ^4.2.0
    '@unocss/nuxt': ^66.5.4
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/nuxt': ^14.0.0
    esbuild: ^0.25.11
    nitropack: ^2.12.9
    # https://github.com/nuxt/nuxt/issues/33418
    nuxt: 4.1.2
    nuxt-mcp: ^0.2.5
    rolldown: ^1.0.0-beta.45
    tsdown: ^0.15.12
    tsx: ^4.20.6
    unplugin-vue: ^7.0.4
    vite: npm:rolldown-vite@^7.1.20
  deps:
    '@pnpm/read-project-manifest': ^1001.1.4
    '@rolldown/debug': ^1.0.0-beta.45
    ansis: ^4.2.0
    birpc: ^2.6.1
    cac: ^6.7.14
    debug: ^4.4.3
    diff: ^8.0.2
    get-port-please: ^3.2.0
    h3: ^1.15.4
    launch-editor: ^2.12.0
    mlly: ^1.8.0
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.2.0
    p-limit: ^7.2.0
    pathe: ^2.0.3
    publint: ^0.3.15
    sirv: ^3.0.2
    split2: ^4.2.0
    structured-clone-es: ^1.0.0
    tinyglobby: ^0.2.15
    unconfig: ^7.3.3
    unstorage: ^1.17.1
    webext-bridge: ^6.0.1
    ws: ^8.18.3
  devtools:
    '@antfu/eslint-config': ^6.2.0
    '@nuxt/devtools': ^3.0.0
    '@nuxt/eslint': ^1.10.0
    '@typescript-eslint/utils': ^8.46.2
    '@unocss/eslint-config': ^66.5.4
    bumpp: ^10.3.1
    eslint: ^9.38.0
    lint-staged: ^16.2.6
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
    vite-plugin-inspect: ^11.3.3
    vue-tsc: ^3.1.2
  docs:
    '@shikijs/vitepress-twoslash': ^3.14.0
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.5
  frontend:
    '@floating-ui/dom': ^1.7.4
    '@vueuse/components': ^14.0.0
    '@vueuse/router': ^14.0.0
    codemirror: ^5.65.20
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    diff-match-patch-es: ^1.0.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    nanovis: ^1.0.0
    splitpanes: ^4.0.4
    theme-vitesse: ^1.0.0
    vite-hot-client: ^2.1.0
    vue: ^3.5.22
    vue-virtual-scroller: ^2.0.0-beta.8
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/codicon': ^1.2.31
    '@iconify-json/fluent': ^1.2.34
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/octicon': ^1.2.16
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/simple-icons': ^1.2.56
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/tabler': ^1.2.23
  inlined:
    '@antfu/utils': ^9.3.0
    stream-json: ^1.9.1
  testing:
    vitest: ^4.0.5
  types:
    '@types/chrome': ^0.1.27
    '@types/codemirror': ^5.60.17
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/diff': ^8.0.0
    '@types/split2': ^4.2.3
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
