packages:
  - packages/*
catalogs:
  build:
    '@nuxt/kit': ^3.17.5
    '@unocss/nuxt': ^66.1.3
    '@vueuse/nuxt': ^13.3.0
    esbuild: ^0.25.5
    nitropack: ^2.11.12
    nuxt: ^3.17.5
    nuxt-mcp: ^0.2.2
    rolldown: nightly
    tsdown: ^0.12.7
    vite: npm:rolldown-vite@^6.3.18
  deps:
    '@rolldown/debug': nightly
    ansis: ^4.1.0
    birpc: ^2.3.0
    cac: ^6.7.14
    diff: ^8.0.2
    get-port-please: ^3.1.2
    h3: ^1.15.3
    launch-editor: ^2.10.0
    mlly: ^1.7.4
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.1.2
    p-limit: ^6.2.0
    pathe: ^2.0.3
    publint: ^0.3.12
    structured-clone-es: ^1.0.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
    unstorage: ^1.16.0
    ws: ^8.18.2
  devtools:
    '@antfu/eslint-config': ^4.13.3
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@typescript-eslint/utils': ^8.33.1
    '@unocss/eslint-config': ^66.1.3
    bumpp: ^10.1.1
    eslint: ^9.28.0
    lint-staged: ^16.1.0
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
    vite-plugin-inspect: ^11.1.0
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/router': ^13.3.0
    codemirror: ^5.65.19
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    diff-match-patch-es: ^1.0.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    nanovis: ^0.1.2
    splitpanes: ^4.0.4
    theme-vitesse: ^0.8.3
    vite-hot-client: ^2.0.4
    vue: ^3.5.16
  icons:
    '@iconify-json/carbon': ^1.2.9
    '@iconify-json/catppuccin': ^1.2.11
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.37
  inlined:
    '@antfu/utils': ^9.2.0
    stream-json: ^1.9.1
  testing:
    vitest: ^3.2.2
  types:
    '@types/codemirror': ^5.60.16
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/diff': ^7.0.2
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
