import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'rpc/index': 'src/rpc/index.ts',
    'rpc/client': 'src/rpc/client.ts',
    'rpc/server': 'src/rpc/server.ts',
    'rpc/presets/index': 'src/rpc/presets/index.ts',
    'rpc/presets/ws/client': 'src/rpc/presets/ws/client.ts',
    'rpc/presets/ws/server': 'src/rpc/presets/ws/server.ts',
    'types/index': 'src/types/index.ts',
    'node/index': 'src/node/index.ts',
    'constants': 'src/constants.ts',
    'utils/events': 'src/utils/events.ts',
    'utils/human-id': 'src/utils/human-id.ts',
    'utils/nanoid': 'src/utils/nanoid.ts',
    'utils/promise': 'src/utils/promise.ts',
    'utils/shared-state': 'src/utils/shared-state.ts',
    'utils/state': 'src/utils/state.ts',
    'utils/when': 'src/utils/when.ts',
    'cli': 'src/cli.ts',
    'build': 'src/build.ts',
    'spa': 'src/spa.ts',
    'vite': 'src/vite.ts',
    'kit': 'src/kit.ts',
    'embedded': 'src/embedded.ts',
    'client': 'src/client.ts',
  },
  tsconfig: '../../tsconfig.base.json',
  clean: true,
  dts: true,
  exports: true,
})
