import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'rpc/index': 'src/rpc/index.ts',
    'rpc/client': 'src/rpc/client.ts',
    'rpc/server': 'src/rpc/server.ts',
    'rpc/transports/ws-client': 'src/rpc/transports/ws-client.ts',
    'rpc/transports/ws-server': 'src/rpc/transports/ws-server.ts',
    'types/index': 'src/types/index.ts',
    'node/index': 'src/node/index.ts',
    'constants': 'src/constants.ts',
    'utils/events': 'src/utils/events.ts',
    'utils/human-id': 'src/utils/human-id.ts',
    'utils/nanoid': 'src/utils/nanoid.ts',
    'utils/promise': 'src/utils/promise.ts',
    'utils/shared-state': 'src/utils/shared-state.ts',
    'utils/state': 'src/utils/state.ts',
    'utils/when': 'src/utils/when.ts',
    'adapters/cli': 'src/adapters/cli.ts',
    'adapters/build': 'src/adapters/build.ts',
    'adapters/spa': 'src/adapters/spa.ts',
    'adapters/vite': 'src/adapters/vite.ts',
    'adapters/kit': 'src/adapters/kit.ts',
    'adapters/embedded': 'src/adapters/embedded.ts',
    'client/index': 'src/client/index.ts',
  },
  tsconfig: '../../tsconfig.base.json',
  clean: true,
  dts: true,
  exports: true,
})
