/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-rolldown/node/agent`
 */
// #region Functions
export declare function DevToolsRolldownAgent(): PluginWithDevTools;
export declare function registerRolldownAgentTools(_: ViteDevToolsNodeContext): void;
// #endregion