/**
 * Generated by tsnapi — public API snapshot of `devframe/build`
 */
// #region Interfaces
export interface BuildStaticOptions {
  outDir: string;
  base?: string;
  distDir?: string;
}
// #endregion

// #region Functions
export declare function buildStatic(_: DevtoolDefinition, _: BuildStaticOptions): Promise<void>;
// #endregion