/**
 * Generated by tsnapi — public API snapshot of `devframe/client`
 */
// #region Interfaces
export interface DevToolsRpcClient {
  events: EventEmitter<RpcClientEvents>;
  readonly isTrusted: boolean | null;
  readonly connectionMeta: ConnectionMeta;
  ensureTrusted: (_?: number) => Promise<boolean>;
  requestTrust: () => Promise<boolean>;
  requestTrustWithToken: (_: string) => Promise<boolean>;
  call: DevToolsRpcClientCall;
  callEvent: DevToolsRpcClientCallEvent;
  callOptional: DevToolsRpcClientCallOptional;
  client: DevToolsClientRpcHost;
  sharedState: RpcSharedStateHost;
  cacheManager: RpcCacheManager;
}
export interface DevToolsRpcClientOptions {
  connectionMeta?: ConnectionMeta;
  baseURL?: string | string[];
  authToken?: string;
  wsOptions?: Partial<WsRpcChannelOptions>;
  rpcOptions?: Partial<BirpcOptions<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions, boolean>>;
  cacheOptions?: boolean | Partial<RpcCacheOptions>;
}
// #endregion

// #region Functions
export declare function connectDevtool(_?: DevToolsRpcClientOptions): Promise<DevToolsRpcClient>;
// #endregion