/**
 * Generated by tsnapi — public API snapshot of `devframe/embedded`
 */
// #region Functions
export declare function registerInHost(_: DevtoolDefinition, _: DevToolsNodeContext): Promise<void>;
// #endregion