/**
 * Generated by tsnapi — public API snapshot of `devframe/node`
 */
// #region Interfaces
export interface CreateH3DevToolsHostOptions {
  app?: unknown;
  origin: string;
  mount?: (_: string, _: string) => void | Promise<void>;
}
export interface CreateHostContextOptions {
  cwd: string;
  workspaceRoot?: string;
  mode: 'dev' | 'build';
  host: DevToolsHost;
  builtinRpcDeclarations?: readonly RpcFunctionDefinitionAny[];
}
export interface CreateStorageOptions<T extends object> {
  filepath: string;
  initialValue: T;
  mergeInitialValue?: false | ((_: T, _: T) => T);
  debounce?: number;
}
export interface DevToolsInternalContext {
  storage: {
    auth: SharedState<InternalAnonymousAuthStorage>;
  };
  revokeAuthToken: (_: string) => Promise<void>;
  remoteTokens: Map<string, RemoteTokenRecord>;
  allocateRemoteToken: (_: string, _: string, _: boolean) => string;
  revokeRemoteToken: (_: string) => void;
  revokeRemoteTokensForDock: (_: string) => void;
  isRemoteTokenTrusted: (_: string, _?: string) => boolean;
  wsEndpoint?: {
    url: string;
  };
}
export interface InternalAnonymousAuthStorage {
  trusted: Record<string, {
    authToken: string;
    ua: string;
    origin: string;
    timestamp: number;
  } | undefined>;
}
export interface PendingAuthRequest {
  clientAuthToken: string;
  session: DevToolsNodeRpcSession;
  ua: string;
  origin: string;
  resolve: (_: {
    isTrusted: boolean;
  }) => void;
  abortController: AbortController;
  timeout: ReturnType<typeof setTimeout>;
}
export interface RemoteTokenRecord {
  dockId: string;
  origin: string;
  originLock: boolean;
}
export interface StartedServer {
  origin: string;
  port: number;
  app: App;
  wss: WebSocketServer;
  rpcGroup: BirpcGroup<DevToolsRpcClientFunctions, DevToolsRpcServerFunctions, false>;
  close: () => Promise<void>;
}
export interface StartHttpAndWsOptions {
  context: DevToolsNodeContext;
  host?: string;
  port: number;
  app?: App;
  onReady?: (_: {
    origin: string;
    port: number;
    app: App;
  }) => void | Promise<void>;
}
export interface StaticRpcDumpCollection {
  manifest: StaticRpcDumpManifest;
  files: Record<string, any>;
}
export interface StaticRpcDumpManifestQueryEntry {
  type: 'query';
  records: Record<string, string>;
  fallback?: string;
}
export interface StaticRpcDumpManifestStaticEntry {
  type: 'static';
  path: string;
}
// #endregion

// #region Types
export type StaticRpcDumpManifest = Record<string, StaticRpcDumpManifestValue>;
export type StaticRpcDumpManifestValue = StaticRpcDumpManifestStaticEntry | StaticRpcDumpManifestQueryEntry | any;
// #endregion

// #region Classes
export declare class DevToolsAgentHost implements DevToolsAgentHost$1 {
  readonly context: DevToolsNodeContext;
  readonly events: EventEmitter<DevToolsAgentHostEvents>;
  private readonly tools;
  private readonly resources;
  private _rpcUnsubscribe;
  constructor(_: DevToolsNodeContext);
  registerTool(_: AgentToolInput): AgentHandle;
  unregisterTool(_: string): boolean;
  registerResource(_: AgentResourceInput): AgentHandle;
  unregisterResource(_: string): boolean;
  list(): AgentManifest;
  getTool(_: string): AgentTool | undefined;
  getResource(_: string): AgentResource | undefined;
  invoke(_: string, _: unknown): Promise<unknown>;
  read(_: string): Promise<AgentResourceContent>;
  _dispose(): void;
  private _validateToolId;
  private _projectTool;
  private _collectRpcTools;
  private _findRpcDefinition;
  private _coercePositionalArgs;
}
export declare class DevToolsCommandsHost implements DevToolsCommandsHost$1 {
  readonly context: DevToolsNodeContext;
  readonly commands: DevToolsCommandsHost$1['commands'];
  readonly events: DevToolsCommandsHost$1['events'];
  constructor(_: DevToolsNodeContext);
  register(_: DevToolsServerCommandInput): DevToolsCommandHandle;
  unregister(_: string): boolean;
  execute(_: string, ..._: any[]): Promise<unknown>;
  list(): DevToolsServerCommandEntry[];
  private findCommand;
  private toSerializable;
}
export declare class DevToolsDockHost implements DevToolsDockHost$1 {
  readonly context: DevToolsNodeContext;
  readonly views: DevToolsDockHost$1['views'];
  readonly events: DevToolsDockHost$1['events'];
  userSettings: SharedState<DevToolsDocksUserSettings>;
  private readonly remoteDocks;
  constructor(_: DevToolsNodeContext);
  init(): Promise<void>;
  values({
    includeBuiltin
  }?: {
    includeBuiltin?: boolean;
  }): DevToolsDockEntry[];
  private projectView;
  private resolveDevServerOrigin;
  register<T extends DevToolsDockUserEntry>(_: T, _?: boolean): {
    update: (_: Partial<T>) => void;
  };
  update(_: DevToolsDockUserEntry): void;
  private prepareRemoteRegistration;
}
export declare class DevToolsLogsHost implements DevToolsLogsHost$1 {
  readonly context: DevToolsNodeContext;
  readonly entries: DevToolsLogsHost$1['entries'];
  readonly events: DevToolsLogsHost$1['events'];
  readonly lastModified: Map<string, number>;
  readonly removals: Array<{
    id: string;
    time: number;
  }>;
  private _autoDeleteTimers;
  private _clock;
  private _tick;
  constructor(_: DevToolsNodeContext);
  add(_: DevToolsLogEntryInput): Promise<DevToolsLogHandle>;
  update(_: string, _: Partial<DevToolsLogEntryInput>): Promise<DevToolsLogEntry | undefined>;
  remove(_: string): Promise<void>;
  clear(): Promise<void>;
  private _createHandle;
}
export declare class DevToolsTerminalHost implements DevToolsTerminalHost$1 {
  readonly context: DevToolsNodeContext;
  readonly sessions: DevToolsTerminalHost$1['sessions'];
  readonly events: DevToolsTerminalHost$1['events'];
  private _boundStreams;
  constructor(_: DevToolsNodeContext);
  register(_: DevToolsTerminalSession): DevToolsTerminalSession;
  update(_: PartialWithoutId<DevToolsTerminalSession>): void;
  remove(_: DevToolsTerminalSession): void;
  private bindStream;
  startChildProcess(_: DevToolsChildProcessExecuteOptions, _: Omit<DevToolsTerminalSessionBase, 'status'>): Promise<DevToolsChildProcessTerminalSession>;
}
export declare class DevToolsViewHost implements DevToolsViewHost$1 {
  readonly context: DevToolsNodeContext;
  buildStaticDirs: {
    baseUrl: string;
    distDir: string;
  }[];
  constructor(_: DevToolsNodeContext);
  hostStatic(_: string, _: string): void;
}
export declare class RpcFunctionsHost extends RpcFunctionsCollectorBase<DevToolsRpcServerFunctions, DevToolsNodeContext> implements RpcFunctionsHost$1 {
  _rpcGroup: BirpcGroup<DevToolsRpcClientFunctions, DevToolsRpcServerFunctions, false>;
  _asyncStorage: AsyncLocalStorage<DevToolsNodeRpcSession>;
  constructor(_: DevToolsNodeContext);
  sharedState: RpcSharedStateHost;
  invokeLocal<T extends keyof DevToolsRpcServerFunctions, Args extends Parameters<DevToolsRpcServerFunctions[T]>>(_: T, ..._: Args): Promise<Awaited<ReturnType<DevToolsRpcServerFunctions[T]>>>;
  broadcast<T extends keyof DevToolsRpcClientFunctions, Args extends Parameters<DevToolsRpcClientFunctions[T]>>(_: RpcBroadcastOptions<T, Args>): Promise<void>;
  getCurrentRpcSession(): DevToolsNodeRpcSession | undefined;
}
// #endregion

// #region Functions
export declare function abortPendingAuth(): void;
export declare function collectStaticRpcDump(_: Iterable<RpcFunctionDefinitionAny>, _: any): Promise<StaticRpcDumpCollection>;
export declare function consumeTempAuthToken(_: string, _: SharedState<InternalAnonymousAuthStorage>): string | null;
export declare function createH3DevToolsHost(_: CreateH3DevToolsHostOptions): DevToolsHost;
export declare function createHostContext(_: CreateHostContextOptions): Promise<DevToolsNodeContext>;
export declare function createRpcSharedStateServerHost(_: RpcFunctionsHost$1): RpcSharedStateHost;
export declare function createStorage<T extends object>(_: CreateStorageOptions<T>): SharedState<T>;
export declare function getInternalContext(_: DevToolsNodeContext): DevToolsInternalContext;
export declare function getPendingAuth(): PendingAuthRequest | null;
export declare function getTempAuthToken(): string;
export declare function isObject(_: unknown): value is Record<string, any>;
export declare function normalizeHttpServerUrl(_: string, _: number | string): string;
export declare function refreshTempAuthToken(): string;
export declare function revokeActiveConnectionsForToken(_: DevToolsNodeContext, _: string): Promise<void>;
export declare function revokeAuthToken(_: DevToolsNodeContext, _: SharedState<InternalAnonymousAuthStorage>, _: string): Promise<void>;
export declare function setPendingAuth(_: PendingAuthRequest | null): void;
export declare function startHttpAndWs(_: StartHttpAndWsOptions): Promise<StartedServer>;
// #endregion

// #region Variables
export declare const ContextUtils: {
  createSimpleClientScript(fn: string | ((ctx: any) => void)): ClientScriptEntry;
};
export declare const internalContextMap: WeakMap<DevToolsNodeContext, DevToolsInternalContext>;
// #endregion