/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc`
 */
// #region Other
export { BirpcFn }
export { BirpcReturn }
export { createClientFromDump }
export { createDefineWrapperWithContext }
export { defineRpcFunction }
export { dumpFunctions }
export { EntriesToObject }
export { getDefinitionsWithDumps }
export { getRpcHandler }
export { getRpcResolvedSetupResult }
export { RpcArgsSchema }
export { RpcCacheManager }
export { RpcCacheOptions }
export { RpcDefinitionsFilter }
export { RpcDefinitionsToFunctions }
export { RpcDump }
export { RpcDumpClientOptions }
export { RpcDumpCollectionOptions }
export { RpcDumpDefinition }
export { RpcDumpGetter }
export { RpcDumpRecord }
export { RpcDumpStore }
export { RpcFunctionAgentOptions }
export { RpcFunctionDefinition }
export { RpcFunctionDefinitionAny }
export { RpcFunctionDefinitionAnyWithContext }
export { RpcFunctionDefinitionBase }
export { RpcFunctionDefinitionToFunction }
export { RpcFunctionsCollector }
export { RpcFunctionsCollectorBase }
export { RpcFunctionSetupResult }
export { RpcFunctionType }
export { RpcReturnSchema }
export { Thenable }
export { validateDefinition }
export { validateDefinitions }
// #endregion