/**
 * Generated by tsnapi — public API snapshot of `devframe/spa`
 */
// #region Interfaces
export interface BuildSpaOptions {
  outDir: string;
  base?: string;
}
// #endregion

// #region Functions
export declare function buildSpa(_: DevtoolDefinition, _: BuildSpaOptions): Promise<void>;
// #endregion