/**
 * Generated by tsnapi — public API snapshot of `devframe/recipes/open-helpers`
 */
// #region Variables
export declare const openHelpers: readonly [{
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], void>>) | undefined;
  handler?: ((args_0: string) => void) | undefined;
  dump?: RpcDump<[string], void, undefined> | undefined;
  snapshot?: boolean;
  __resolved?: RpcFunctionSetupResult<[string], void> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], void>> | undefined;
}, {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], void>>) | undefined;
  handler?: ((args_0: string) => void) | undefined;
  dump?: RpcDump<[string], void, undefined> | undefined;
  snapshot?: boolean;
  __resolved?: RpcFunctionSetupResult<[string], void> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], void>> | undefined;
}];
export declare const openInEditor: {
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], void>>) | undefined;
  handler?: ((args_0: string) => void) | undefined;
  dump?: RpcDump<[string], void, undefined> | undefined;
  snapshot?: boolean;
  __resolved?: RpcFunctionSetupResult<[string], void> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], void>> | undefined;
};
export declare const openInFinder: {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], void>>) | undefined;
  handler?: ((args_0: string) => void) | undefined;
  dump?: RpcDump<[string], void, undefined> | undefined;
  snapshot?: boolean;
  __resolved?: RpcFunctionSetupResult<[string], void> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], void>> | undefined;
};
// #endregion