/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-vite`
 */
// #region Interfaces
export interface ViteInspectErrorInfo {
  message: string;
  stack: string[];
  raw?: unknown;
}
export interface ViteInspectMiddlewareMetric {
  self: number;
  total: number;
  name: string;
}
export interface ViteInspectModuleInfo {
  id: string;
  deps: string[];
  importers: string[];
  plugins: ViteInspectModulePluginMetric[];
  virtual: boolean;
  totalTime: number;
  invokeCount: number;
  sourceSize: number;
  distSize: number;
}
export interface ViteInspectModulePluginMetric {
  name: string;
  transform?: number;
  resolveId?: number;
}
export interface ViteInspectModuleTransformInfo {
  resolvedId: string;
  transforms: ViteInspectTransformInfo[];
}
export interface ViteInspectPluginCallInfo {
  type: ViteInspectPluginCallType;
  id: string;
  duration: number;
  plugin_id: number;
  plugin_name: string;
  module: string;
  graphModuleId?: string;
  timestamp_start: number;
  timestamp_end: number;
  unchanged?: boolean;
}
export interface ViteInspectPluginDetails {
  plugin_name: string;
  plugin_id: number;
  calls: ViteInspectPluginCallInfo[];
  resolveIdMetrics: ViteInspectPluginCallInfo[];
  loadMetrics: ViteInspectPluginCallInfo[];
  transformMetrics: ViteInspectPluginCallInfo[];
}
export interface ViteInspectPluginMetric {
  name: string;
  plugin_id?: number;
  enforce?: 'pre' | 'post';
  transform: {
    invokeCount: number;
    totalTime: number;
  };
  resolveId: {
    invokeCount: number;
    totalTime: number;
  };
}
export interface ViteInspectQuery {
  vite: string;
  env: string;
}
export interface ViteInspectResolveIdInfo {
  name: string;
  plugin_id?: number;
  result: string;
  start: number;
  end: number;
  error?: unknown;
}
export interface ViteInspectServerMetrics {
  middleware: Record<string, ViteInspectMiddlewareMetric[]>;
}
export interface ViteInspectTransformInfo {
  name: string;
  plugin_id?: number;
  result?: string | null;
  start: number;
  end: number;
  order?: string;
  sourcemaps?: unknown;
  error?: ViteInspectErrorInfo;
}
// #endregion

// #region Types
export type ViteInspectPluginCallType = 'resolve' | 'load' | 'transform';
// #endregion

// #region Functions
export declare function DevToolsViteInspect(): PluginWithDevTools;
export declare function DevToolsViteUI(): PluginOption;
export declare function DevToolsViteUIPlugin(): PluginWithDevTools;
// #endregion