/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/cli`
 */
// #region Interfaces
export interface CliHandle {
  cli: CAC;
  parse: (_?: string[]) => Promise<void>;
}
export interface CreateCliOptions {
  defaultPort?: number;
  configureCli?: (_: CAC) => void;
  onReady?: (_: {
    origin: string;
    port: number;
    app: App;
  }) => void | Promise<void>;
}
// #endregion

// #region Functions
export declare function createCli(_: DevtoolDefinition, _?: CreateCliOptions): CliHandle;
// #endregion