/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/dev`
 */
// #region Interfaces
export interface CreateDevServerOptions {
  host?: string;
  port?: number;
  flags?: Record<string, unknown>;
  distDir?: string;
  basePath?: string;
  app?: App;
  openBrowser?: boolean | string;
  onReady?: (_: {
    origin: string;
    port: number;
    app: App;
  }) => void | Promise<void>;
}
export interface ResolveDevServerPortOptions {
  host?: string;
  defaultPort?: number;
}
// #endregion

// #region Functions
export declare function createDevServer(_: DevframeDefinition, _?: CreateDevServerOptions): Promise<StartedServer>;
export declare function resolveDevServerPort(_: DevframeDefinition, _?: ResolveDevServerPortOptions): Promise<number>;
// #endregion