/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/client`
 */
// #region Functions
export declare function getDevToolsClientContext(): DevToolsClientContext | undefined;
export declare function getDevToolsRpcClient(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
// #endregion

// #region Variables
export declare const CLIENT_CONTEXT_KEY: string;
// #endregion

// #region Other
export { attachDevToolsFrameNav }
export { CommandsContext }
export { connectRemoteDevTools }
export { ConnectRemoteDevToolsOptions }
export { DevToolsClientContext }
export { DevToolsClientRpcHost }
export { DevToolsFrameNavClient }
export { DevToolsFrameNavClientOptions }
export { DevToolsFrameNavEnvelope }
export { DevToolsFrameNavFrameMessage }
export { DevToolsFrameNavHostMessage }
export { DevToolsFrameNavHostPayload }
export { DevToolsFrameNavListenTarget }
export { DevToolsFrameTab }
export { DevToolsRpcClient }
export { DevToolsRpcClientCall }
export { DevToolsRpcClientCallEvent }
export { DevToolsRpcClientCallOptional }
export { DevToolsRpcClientMode }
export { DevToolsRpcClientOptions }
export { DevToolsRpcContext }
export { DockClientScriptContext }
export { DockClientType }
export { DockEntryState }
export { DockEntryStateEvents }
export { DockPanelStorage }
export { DockRegistration }
export { DockRenderer }
export { DockRendererInstance }
export { DockRendererMountOptions }
export { DockRenderersContext }
export { DocksContext }
export { DocksEntriesContext }
export { DocksPanelContext }
export { FRAME_NAV_CHANNEL }
export { FRAME_NAV_VERSION }
export { parseRemoteConnection }
export { RpcClientEvents }
export { RpcStreamingClientHost }
export { StreamingSubscribeOptions }
export { WhenClauseContext }
// #endregion