/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/client`
 */
// #region Interfaces
export interface CommandsContext {
  readonly commands: DevToolsCommandEntry[];
  readonly paletteCommands: DevToolsCommandEntry[];
  register: (_: DevToolsClientCommand | DevToolsClientCommand[]) => () => void;
  execute: (_: string, ..._: any[]) => Promise<unknown>;
  getKeybindings: (_: string) => DevToolsCommandKeybinding[];
  settings: shared_state_d_exports.SharedState<DevToolsDocksUserSettings>;
  paletteOpen: boolean;
}
export interface DevToolsRpcClient {
  events: EventEmitter<RpcClientEvents>;
  readonly isTrusted: boolean | null;
  readonly connectionMeta: ConnectionMeta;
  ensureTrusted: (_?: number) => Promise<boolean>;
  requestTrust: () => Promise<boolean>;
  requestTrustWithToken: (_: string) => Promise<boolean>;
  call: DevToolsRpcClientCall;
  callEvent: DevToolsRpcClientCallEvent;
  callOptional: DevToolsRpcClientCallOptional;
  client: DevToolsClientRpcHost;
  sharedState: RpcSharedStateHost;
  cacheManager: RpcCacheManager;
}
export interface DevToolsRpcClientMode {
  readonly isTrusted: boolean;
  ensureTrusted: DevToolsRpcClient['ensureTrusted'];
  requestTrust: DevToolsRpcClient['requestTrust'];
  requestTrustWithToken: DevToolsRpcClient['requestTrustWithToken'];
  call: DevToolsRpcClient['call'];
  callEvent: DevToolsRpcClient['callEvent'];
  callOptional: DevToolsRpcClient['callOptional'];
}
export interface DevToolsRpcClientOptions {
  connectionMeta?: ConnectionMeta;
  baseURL?: string | string[];
  authToken?: string;
  wsOptions?: Partial<WsRpcChannelOptions>;
  rpcOptions?: Partial<BirpcOptions<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions, boolean>>;
  cacheOptions?: boolean | Partial<RpcCacheOptions>;
}
export interface DevToolsRpcContext {
  readonly rpc: DevToolsRpcClient;
}
export interface DockClientScriptContext extends DocksContext {
  current: DockEntryState;
  logs: DevToolsLogsClient;
}
export interface DockEntryState {
  entryMeta: DevToolsDockEntry;
  readonly isActive: boolean;
  domElements: {
    iframe?: HTMLIFrameElement | null;
    panel?: HTMLDivElement | null;
  };
  events: EventEmitter<DockEntryStateEvents>;
}
export interface DockEntryStateEvents {
  'entry:activated': () => void;
  'entry:deactivated': () => void;
  'entry:updated': (_: DevToolsDockUserEntry) => void;
  'dom:panel:mounted': (_: HTMLDivElement) => void;
  'dom:iframe:mounted': (_: HTMLIFrameElement) => void;
}
export interface DockPanelStorage {
  mode: 'float' | 'edge';
  width: number;
  height: number;
  top: number;
  left: number;
  position: 'left' | 'right' | 'bottom' | 'top';
  open: boolean;
  inactiveTimeout: number;
}
export interface DocksContext extends DevToolsRpcContext {
  readonly clientType: 'embedded' | 'standalone';
  readonly panel: DocksPanelContext;
  readonly docks: DocksEntriesContext;
  readonly commands: CommandsContext;
  readonly when: WhenClauseContext;
}
export interface DocksEntriesContext {
  selectedId: string | null;
  readonly selected: DevToolsDockEntry | null;
  entries: DevToolsDockEntry[];
  entryToStateMap: Map<string, DockEntryState>;
  groupedEntries: DevToolsDockEntriesGrouped;
  settings: shared_state_d_exports.SharedState<DevToolsDocksUserSettings>;
  getStateById: (_: string) => DockEntryState | undefined;
  switchEntry: (_?: string | null) => Promise<boolean>;
  toggleEntry: (_: string) => Promise<boolean>;
}
export interface DocksPanelContext {
  store: DockPanelStorage;
  isDragging: boolean;
  isResizing: boolean;
  readonly isVertical: boolean;
}
export interface RpcClientEvents {
  'rpc:is-trusted:updated': (_: boolean) => void;
}
export interface WhenClauseContext {
  readonly context: when_d_exports.WhenContext;
}
// #endregion

// #region Types
export type ConnectRemoteDevToolsOptions = Omit<DevToolsRpcClientOptions, 'connectionMeta' | 'authToken'>;
export type DevToolsClientContext = DocksContext;
export type DevToolsClientRpcHost = RpcFunctionsCollector<DevToolsRpcClientFunctions, DevToolsRpcContext>;
export type DevToolsRpcClientCall = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$call'];
export type DevToolsRpcClientCallEvent = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$callEvent'];
export type DevToolsRpcClientCallOptional = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$callOptional'];
export type DockClientType = 'embedded' | 'standalone';
// #endregion

// #region Functions
export declare function connectRemoteDevTools(_?: ConnectRemoteDevToolsOptions): Promise<DevToolsRpcClient>;
export declare function getDevToolsClientContext(): DevToolsClientContext | undefined;
export declare function getDevToolsRpcClient(_?: DevToolsRpcClientOptions): Promise<DevToolsRpcClient>;
export declare function parseRemoteConnection(_?: string): RemoteConnectionInfo | null;
// #endregion

// #region Variables
export declare const CLIENT_CONTEXT_KEY: string;
// #endregion