/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/constants`
 */
// #region Variables
export declare const DEFAULT_CATEGORIES_ORDER: Record<string, number>;
export declare const DEFAULT_STATE_USER_SETTINGS: () => DevToolsDocksUserSettings;
// #endregion

// #region Re-exports
export * from "devframe/constants";
// #endregion