/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/constants`
 */
// #region Variables
export declare const DEFAULT_CATEGORIES_ORDER: Record<string, number>;
export declare const DEVTOOLS_DIRNAME: string;
export declare const DEVTOOLS_DOCK_IMPORTS_VIRTUAL_ID: string;
export declare const DEVTOOLS_INSPECTOR_DOCK_ID: string;
export declare const DEVTOOLS_MOUNT_PATH: string;
export declare const DEVTOOLS_MOUNT_PATH_NO_TRAILING_SLASH: string;
export declare const DEVTOOLS_TERMINALS_DOCK_ID: string;
export declare const DEVTOOLS_VITEPLUS_GROUP_ID: string;
export declare const DEVTOOLS_WS_PATH: string;
export declare const DEVTOOLS_WS_ROUTE: string;
// #endregion

// #region Other
export { DEFAULT_STATE_USER_SETTINGS }
export { DEVTOOLS_CONNECTION_META_FILENAME }
export { DEVTOOLS_DOCK_IMPORTS_FILENAME }
export { DEVTOOLS_RPC_DUMP_DIRNAME }
export { DEVTOOLS_RPC_DUMP_MANIFEST_FILENAME }
export { DevToolsDocksUserSettings }
export { REMOTE_CONNECTION_KEY }
// #endregion