/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit`
 */
// #region Types
export type WhenContext = when_d_exports.WhenContext;
export type WhenExpression = when_d_exports.WhenExpression;
// #endregion

// #region Functions
export declare function defineCommand<const W extends string = ''>(_: Omit<DevToolsServerCommandInput, 'when'> & {
  when?: when_d_exports.WhenExpression<when_d_exports.WhenContext, W>;
}): DevToolsServerCommandInput;
export declare function defineDockEntry<const T extends DevToolsDockUserEntry, const W extends string = ''>(_: Omit<T, 'when'> & {
  when?: when_d_exports.WhenExpression<when_d_exports.WhenContext, W>;
}): T;
export declare function defineJsonRenderSpec(_: JsonRenderSpec): JsonRenderSpec;
// #endregion

// #region Variables
export declare const defineRpcFunction: <NAME extends string, TYPE extends _$devframe_rpc0.RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends _$devframe_rpc0.RpcArgsSchema | undefined = undefined, const RS extends _$devframe_rpc0.RpcReturnSchema | undefined = undefined>(definition: _$devframe_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, ViteDevToolsNodeContext>) => _$devframe_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, ViteDevToolsNodeContext>;
// #endregion

// #region Other
export { ClientScriptEntry }
export { ConnectionMeta }
export { DevToolsCapabilities }
export { DevToolsChildProcessExecuteOptions }
export { DevToolsChildProcessTerminalSession }
export { DevToolsClientCommand }
export { DevToolsCommandBase }
export { DevToolsCommandEntry }
export { DevToolsCommandHandle }
export { DevToolsCommandKeybinding }
export { DevToolsCommandShortcutOverrides }
export { DevToolsCommandsHost }
export { DevToolsCommandsHostEvents }
export { DevToolsDockEntriesGrouped }
export { DevToolsDockEntry }
export { DevToolsDockEntryBase }
export { DevToolsDockEntryCategory }
export { DevToolsDockEntryIcon }
export { DevToolsDockHost }
export { DevToolsDocksUserSettings }
export { DevToolsDockUserEntry }
export { DevToolsHost }
export { DevToolsLogElementPosition }
export { DevToolsLogEntry }
export { DevToolsLogEntryFrom }
export { DevToolsLogEntryInput }
export { DevToolsLogFilePosition }
export { DevToolsLogHandle }
export { DevToolsLogLevel }
export { DevToolsLogsClient }
export { DevToolsLogsHost }
export { DevToolsNodeContext }
export { DevToolsNodeRpcSession }
export { DevToolsNodeUtils }
export { DevToolsPluginOptions }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsServerCommandEntry }
export { DevToolsServerCommandInput }
export { DevToolsTerminalHost }
export { DevToolsTerminalSession }
export { DevToolsTerminalSessionBase }
export { DevToolsTerminalSessionStreamChunkEvent }
export { DevToolsTerminalStatus }
export { DevToolsViewAction }
export { DevToolsViewBuiltin }
export { DevToolsViewCustomRender }
export { DevToolsViewHost }
export { DevToolsViewIframe }
export { DevToolsViewJsonRender }
export { DevToolsViewLauncher }
export { DevToolsViewLauncherStatus }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { JsonRenderElement }
export { JsonRenderer }
export { JsonRenderSpec }
export { PartialWithoutId }
export { PluginWithDevTools }
export { RemoteConnectionInfo }
export { RemoteDockOptions }
export { RpcBroadcastOptions }
export { RpcDefinitionsFilter }
export { RpcDefinitionsToFunctions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { Thenable }
export { ViteDevToolsNodeContext }
// #endregion