/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit`
 */
// #region Variables
export declare const defineRpcFunction: <NAME extends string, TYPE extends import("devframe/rpc").RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends import("devframe/rpc").RpcArgsSchema | undefined = undefined, const RS extends import("devframe/rpc").RpcReturnSchema | undefined = undefined>(definition: import("devframe/rpc").RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, ViteDevToolsNodeContext>) => import("devframe/rpc").RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, ViteDevToolsNodeContext>;
// #endregion

// #region Other
export { ClientScriptEntry }
export { ConnectionMeta }
export { CreateKitContextOptions }
export { defineCommand }
export { defineDockEntry }
export { defineJsonRenderSpec }
export { DevToolsCapabilities }
export { DevToolsChildProcessExecuteOptions }
export { DevToolsChildProcessTerminalSession }
export { DevToolsClientCommand }
export { DevToolsCommandBase }
export { DevToolsCommandEntry }
export { DevToolsCommandHandle }
export { DevToolsCommandKeybinding }
export { DevToolsCommandShortcutOverrides }
export { DevToolsCommandsHost }
export { DevToolsCommandsHostEvents }
export { DevToolsDiagnosticsDefinition }
export { DevToolsDiagnosticsHost }
export { DevToolsDiagnosticsLogger }
export { DevToolsDockEntriesGrouped }
export { DevToolsDockEntry }
export { DevToolsDockEntryBase }
export { DevToolsDockEntryCategory }
export { DevToolsDockEntryIcon }
export { DevToolsDockHost }
export { DevToolsDocksUserSettings }
export { DevToolsDockUserEntry }
export { DevToolsHost }
export { DevToolsMessageElementPosition }
export { DevToolsMessageEntry }
export { DevToolsMessageEntryFrom }
export { DevToolsMessageEntryInput }
export { DevToolsMessageFilePosition }
export { DevToolsMessageHandle }
export { DevToolsMessageLevel }
export { DevToolsMessagesClient }
export { DevToolsMessagesHost }
export { DevToolsNodeContext }
export { DevToolsNodeRpcSession }
export { DevToolsPluginOptions }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsServerCommandEntry }
export { DevToolsServerCommandInput }
export { DevToolsTerminalHost }
export { DevToolsTerminalSession }
export { DevToolsTerminalSessionBase }
export { DevToolsTerminalStatus }
export { DevToolsViewAction }
export { DevToolsViewBuiltin }
export { DevToolsViewCustomRender }
export { DevToolsViewGroup }
export { DevToolsViewHost }
export { DevToolsViewIframe }
export { DevToolsViewJsonRender }
export { DevToolsViewLauncher }
export { DevToolsViewLauncherStatus }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { JsonRenderElement }
export { JsonRenderer }
export { JsonRenderSpec }
export { KitNodeContext }
export { PartialWithoutId }
export { PluginWithDevTools }
export { RemoteConnectionInfo }
export { RemoteDockOptions }
export { RpcBroadcastOptions }
export { RpcDefinitionsFilter }
export { RpcDefinitionsToFunctions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { RpcStreamingChannel }
export { RpcStreamingChannelOptions }
export { RpcStreamingHost }
export { Thenable }
export { ViteDevToolsNodeContext }
// #endregion