/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/node`
 */
// #region Interfaces
export interface CreateKitContextOptions extends CreateHubContextOptions {
  viteConfig?: ResolvedConfig;
  viteServer?: ViteDevServer;
}
export interface CreatePluginFromDevframeOptions {
  name?: string;
  base?: string;
  dock?: Partial<Omit<DevframeViewIframe, 'id' | 'type' | 'url'>>;
  capabilities?: DevframeCapabilities | {
    dev?: DevframeCapabilities | boolean;
    build?: DevframeCapabilities | boolean;
  };
  setup?: (_: KitNodeContext) => void | Promise<void>;
}
export interface CreateViteDevToolsHostOptions {
  viteConfig: ResolvedConfig;
  viteServer?: ViteDevServer;
  workspaceRoot?: string;
}
export interface KitNodeContext extends DevframeHubContext {
  readonly viteConfig?: ResolvedConfig;
  readonly viteServer?: ViteDevServer;
}
// #endregion

// #region Functions
export declare function createKitContext(_: CreateKitContextOptions): Promise<KitNodeContext>;
export declare function createPluginFromDevframe(_: DevframeDefinition, _?: CreatePluginFromDevframeOptions): PluginWithDevTools;
export declare function createSimpleClientScript(_: string | ((_: any) => void)): ClientScriptEntry;
export declare function createViteDevToolsHost(_: CreateViteDevToolsHostOptions): DevframeHost;
// #endregion

// #region Other
export { DevToolsCommandsHost }
export { DevToolsDockHost }
export { DevToolsMessagesHost }
export { DevToolsTerminalHost }
export { mountDevframe }
// #endregion