/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/when`
 */
// #region Interfaces
export interface WhenContext {
  clientType: 'embedded' | 'standalone';
  dockOpen: boolean;
  paletteOpen: boolean;
  dockSelectedId: string;
  [key: string]: unknown;
}
// #endregion

// #region Types
export type WhenExpression = _$whenexpr0.WhenExpression;
// #endregion

// #region Functions
export declare function evaluateWhen<T extends object, const E extends string>(_: E & _$whenexpr0.ValidateExpression<E, T>, _: T, _?: _$whenexpr0.EvaluateOptions): boolean;
export declare function resolveContextValue<T extends Record<string, unknown>>(_: string, _: T): unknown;
// #endregion
