/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/when`
 */
// #region Interfaces
export interface WhenContext {
  clientType: 'embedded' | 'standalone';
  dockOpen: boolean;
  paletteOpen: boolean;
  dockSelectedId: string;
  [key: string]: unknown;
}
// #endregion

// #region Functions
export declare function evaluateWhen(_: string, _: WhenContext): boolean;
export declare function getContextValue(_: string, _: WhenContext): unknown;
// #endregion