/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/colors`
 */
// #region Interfaces
export interface ColorFn {
  (_: unknown): string;
  (_: TemplateStringsArray, ..._: unknown[]): string;
}
export interface Colors {
  blue: ColorFn;
  cyan: ColorFn;
  gray: ColorFn;
  green: ColorFn;
  red: ColorFn;
  yellow: ColorFn;
  bold: ColorFn;
  dim: ColorFn;
  reset: ColorFn;
  underline: ColorFn;
}
// #endregion

// #region Variables
export declare const colors: Colors;
// #endregion