/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/events`
 */
// #region Functions
export declare function createEventEmitter<Events extends EventsMap>(): EventEmitter<Events>;
// #endregion