/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/open`
 */
// #region Interfaces
export interface OpenOptions {
  wait?: boolean;
}
// #endregion

// #region Functions
export declare function open(_: string, _?: OpenOptions): Promise<void>;
// #endregion