/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/promise`
 */
// #region Functions
export declare function promiseWithResolver<T>(): {
  promise: Promise<T>;
  resolve: (_: T) => void;
  reject: (_: Error) => void;
};
// #endregion