/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/shared-state`
 */
// #region Other
export { createSharedState }
export { Immutable }
export { ImmutableArray }
export { ImmutableMap }
export { ImmutableObject }
export { ImmutableSet }
export { SharedState }
export { SharedStateEvents }
export { SharedStateOptions }
export { Patch as SharedStatePatch }
// #endregion