/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/state`
 */
// #region Interfaces
export interface SharedState<T> {
  get: () => Immutable<T>;
  on: EventEmitter<SharedStateEvents<T>>['on'];
  mutate: (_: (_: T) => void) => void;
  patch: (_: Patch[]) => void;
}
export interface SharedStateEvents<T> {
  updated: (_: T) => void;
  patches: (_: Patch[]) => void;
}
export interface SharedStateOptions<T> {
  initialState: T;
  enablePatches?: boolean;
}
// #endregion

// #region Types
export type Immutable<T> = T extends ImmutablePrimitive ? T : T extends Array<infer U> ? ImmutableArray<U> : T extends Map<infer K, infer V> ? ImmutableMap<K, V> : T extends Set<infer M> ? ImmutableSet<M> : ImmutableObject<T>;
export type ImmutableArray<T> = ReadonlyArray<Immutable<T>>;
export type ImmutableMap<K, V> = ReadonlyMap<Immutable<K>, Immutable<V>>;
export type ImmutableObject<T> = { readonly [K in keyof T]: Immutable<T[K]> };
export type ImmutableSet<T> = ReadonlySet<Immutable<T>>;
// #endregion

// #region Functions
export declare function createSharedState<T extends Objectish>(_: SharedStateOptions<T>): SharedState<T>;
// #endregion