/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/streaming-channel`
 */
// #region Other
export { BufferedChunk }
export { createStreamReader }
export { CreateStreamReaderOptions }
export { createStreamSink }
export { CreateStreamSinkOptions }
export { StreamErrorPayload }
export { StreamReader }
export { StreamSink }
export { StreamSinkEvents }
// #endregion