/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/structured-clone`
 */
// #region Functions
export declare function structuredCloneDeserialize<T = unknown>(_: unknown[]): T;
export declare function structuredCloneParse<T = unknown>(_: string): T;
export declare function structuredCloneSerialize(_: unknown): unknown[];
export declare function structuredCloneStringify(_: unknown): string;
// #endregion