/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/when`
 */
// #region Interfaces
export interface EvaluateWhenOptions {
  strict?: boolean;
}
export interface WhenContext {
  clientType: 'embedded' | 'standalone';
  dockOpen: boolean;
  paletteOpen: boolean;
  dockSelectedId: string;
  [key: string]: unknown;
}
// #endregion

// #region Types
export type WhenExpression<T, S extends string> = WhenExpression$1<T, S>;
// #endregion

// #region Functions
export declare function evaluateWhen<T extends object, const E extends string>(_: E & WhenExpression$1<T, E>, _: T, _?: EvaluateWhenOptions): boolean;
export declare function resolveContextValue<T extends Record<string, unknown>>(_: string, _: T): unknown;
// #endregion