/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/when`
 */
// #region Interfaces
export interface WhenContext {
  clientType: 'embedded' | 'standalone';
  dockOpen: boolean;
  paletteOpen: boolean;
  dockSelectedId: string;
  [key: string]: unknown;
}
// #endregion

// #region Types
export type WhenExpression<T, S extends string> = S & ValidateExpression<S, T>;
// #endregion

// #region Functions
export declare function evaluateWhen<T extends object, const E extends string>(_: E & ValidateExpression<E, T>, _: T, _?: EvaluateOptions): boolean;
export declare function resolveContextValue<T extends Record<string, unknown>>(_: string, _: T): unknown;
// #endregion