/**
 * Generated by tsnapi — public API snapshot of `devframe/client`
 */
// #region Interfaces
export interface DevToolsRpcClient {
  events: EventEmitter<RpcClientEvents>;
  readonly isTrusted: boolean | null;
  readonly connectionMeta: ConnectionMeta;
  ensureTrusted: (_?: number) => Promise<boolean>;
  requestTrust: () => Promise<boolean>;
  requestTrustWithToken: (_: string) => Promise<boolean>;
  call: DevToolsRpcClientCall;
  callEvent: DevToolsRpcClientCallEvent;
  callOptional: DevToolsRpcClientCallOptional;
  client: DevToolsClientRpcHost;
  sharedState: RpcSharedStateHost;
  streaming: RpcStreamingClientHost;
  cacheManager: RpcCacheManager;
}
export interface DevToolsRpcClientMode {
  readonly isTrusted: boolean;
  ensureTrusted: DevToolsRpcClient['ensureTrusted'];
  requestTrust: DevToolsRpcClient['requestTrust'];
  requestTrustWithToken: DevToolsRpcClient['requestTrustWithToken'];
  call: DevToolsRpcClient['call'];
  callEvent: DevToolsRpcClient['callEvent'];
  callOptional: DevToolsRpcClient['callOptional'];
}
export interface DevToolsRpcClientOptions {
  connectionMeta?: ConnectionMeta;
  baseURL?: string | string[];
  authToken?: string;
  wsOptions?: Partial<WsRpcChannelOptions>;
  rpcOptions?: Partial<BirpcOptions<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions, boolean>>;
  cacheOptions?: boolean | Partial<RpcCacheOptions>;
}
export interface DevToolsRpcContext {
  readonly rpc: DevToolsRpcClient;
}
export interface RpcClientEvents {
  'rpc:is-trusted:updated': (_: boolean) => void;
}
export interface RpcStreamingClientHost {
  subscribe: <T = unknown>(_: string, _: string, _?: StreamingSubscribeOptions) => StreamReader<T>;
  upload: <T = unknown>(_: string, _: string) => StreamSink<T>;
}
export interface StreamingSubscribeOptions {
  highWaterMark?: number;
}
// #endregion

// #region Types
export type DevToolsClientRpcHost = RpcFunctionsCollector<DevToolsRpcClientFunctions, DevToolsRpcContext>;
export type DevToolsRpcClientCall = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$call'];
export type DevToolsRpcClientCallEvent = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$callEvent'];
export type DevToolsRpcClientCallOptional = BirpcReturn<DevToolsRpcServerFunctions, DevToolsRpcClientFunctions>['$callOptional'];
// #endregion

// #region Functions
export declare function connectDevtool(..._: Parameters<typeof getDevToolsRpcClient>): ReturnType<typeof getDevToolsRpcClient>;
export declare function createRpcStreamingClientHost(_: DevToolsRpcClient): RpcStreamingClientHost;
export declare function getDevToolsRpcClient(_?: DevToolsRpcClientOptions): Promise<DevToolsRpcClient>;
// #endregion

// #region Variables
export declare const connectDevframe: typeof getDevToolsRpcClient;
// #endregion