/**
 * Generated by tsnapi — public API snapshot of `devframe/constants`
 */
// #region Variables
export declare const DEFAULT_CATEGORIES_ORDER: Record<string, number>;
export declare const DEFAULT_STATE_USER_SETTINGS: () => DevToolsDocksUserSettings;
export declare const DEVTOOLS_CONNECTION_META_FILENAME: string;
export declare const DEVTOOLS_DIRNAME: string;
export declare const DEVTOOLS_DOCK_IMPORTS_FILENAME: string;
export declare const DEVTOOLS_DOCK_IMPORTS_VIRTUAL_ID: string;
export declare const DEVTOOLS_MOUNT_PATH: string;
export declare const DEVTOOLS_MOUNT_PATH_NO_TRAILING_SLASH: string;
export declare const DEVTOOLS_RPC_DUMP_DIRNAME: string;
export declare const DEVTOOLS_RPC_DUMP_MANIFEST_FILENAME: string;
export declare const REMOTE_CONNECTION_KEY: string;
// #endregion