/**
 * Generated by tsnapi — public API snapshot of `devframe`
 */
// #region Variables
export declare const defineRpcFunction: <NAME extends string, TYPE extends RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends RpcArgsSchema | undefined = undefined, const RS extends RpcReturnSchema | undefined = undefined>(definition: RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>) => RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>;
// #endregion

// #region Other
export { AgentHandle }
export { AgentManifest }
export { AgentResource }
export { AgentResourceContent }
export { AgentResourceInput }
export { AgentTool }
export { AgentToolInput }
export { ConnectionMeta }
export { defineDevframe }
export { defineDevtool }
export { DevframeBrowserContext }
export { DevframeCliOptions }
export { DevframeDefinition }
export { DevframeDeploymentKind }
export { DevframeRuntime }
export { DevframeSetupInfo }
export { DevframeSpaOptions }
export { DevtoolBrowserContext }
export { DevtoolCliOptions }
export { DevtoolDefinition }
export { DevtoolDeploymentKind }
export { DevtoolRuntime }
export { DevToolsAgentHost }
export { DevToolsAgentHostEvents }
export { DevToolsCapabilities }
export { DevToolsDiagnosticsDefinition }
export { DevToolsDiagnosticsHost }
export { DevToolsDiagnosticsLogger }
export { DevtoolSetupInfo }
export { DevToolsHost }
export { DevToolsNodeContext }
export { DevToolsNodeRpcSession }
export { DevToolsNodeRpcSessionMeta }
export { DevtoolSpaOptions }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsViewHost }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { PartialWithoutId }
export { RpcBroadcastOptions }
export { RpcFunctionAgentOptions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { RpcStreamingChannel }
export { RpcStreamingChannelOptions }
export { RpcStreamingHost }
export { Thenable }
// #endregion