/**
 * Generated by tsnapi — public API snapshot of `devframe`
 */
// #region Functions
export declare function defineCommand(_: DevToolsServerCommandInput): DevToolsServerCommandInput;
export declare function defineJsonRenderSpec(_: JsonRenderSpec): JsonRenderSpec;
// #endregion

// #region Variables
export declare const defineRpcFunction: <NAME extends string, TYPE extends RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends RpcArgsSchema | undefined = undefined, const RS extends RpcReturnSchema | undefined = undefined>(definition: RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>) => RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>;
// #endregion

// #region Other
export { AgentHandle }
export { AgentManifest }
export { AgentResource }
export { AgentResourceContent }
export { AgentResourceInput }
export { AgentTool }
export { AgentToolInput }
export { ClientScriptEntry }
export { CliFlagsSchema }
export { ConnectionMeta }
export { defineCliFlags }
export { defineDevtool }
export { DevtoolBrowserContext }
export { DevtoolCliOptions }
export { DevtoolDefinition }
export { DevtoolDeploymentKind }
export { DevtoolRuntime }
export { DevToolsAgentHost }
export { DevToolsAgentHostEvents }
export { DevToolsCapabilities }
export { DevToolsChildProcessExecuteOptions }
export { DevToolsChildProcessTerminalSession }
export { DevToolsClientCommand }
export { DevToolsCommandBase }
export { DevToolsCommandEntry }
export { DevToolsCommandHandle }
export { DevToolsCommandKeybinding }
export { DevToolsCommandShortcutOverrides }
export { DevToolsCommandsHost }
export { DevToolsCommandsHostEvents }
export { DevToolsDockEntriesGrouped }
export { DevToolsDockEntry }
export { DevToolsDockEntryBase }
export { DevToolsDockEntryCategory }
export { DevToolsDockEntryIcon }
export { DevToolsDockHost }
export { DevToolsDocksUserSettings }
export { DevToolsDockUserEntry }
export { DevtoolSetupInfo }
export { DevToolsHost }
export { DevToolsLogElementPosition }
export { DevToolsLogEntry }
export { DevToolsLogEntryFrom }
export { DevToolsLogEntryInput }
export { DevToolsLogFilePosition }
export { DevToolsLogHandle }
export { DevToolsLogLevel }
export { DevToolsLogsClient }
export { DevToolsLogsHost }
export { DevToolsNodeContext }
export { DevToolsNodeRpcSession }
export { DevToolsNodeRpcSessionMeta }
export { DevToolsNodeUtils }
export { DevtoolSpaOptions }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsServerCommandEntry }
export { DevToolsServerCommandInput }
export { DevToolsTerminalHost }
export { DevToolsTerminalSession }
export { DevToolsTerminalSessionBase }
export { DevToolsTerminalSessionStreamChunkEvent }
export { DevToolsTerminalStatus }
export { DevToolsViewAction }
export { DevToolsViewBuiltin }
export { DevToolsViewCustomRender }
export { DevToolsViewHost }
export { DevToolsViewIframe }
export { DevToolsViewJsonRender }
export { DevToolsViewLauncher }
export { DevToolsViewLauncherStatus }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { InferCliFlags }
export { JsonRenderElement }
export { JsonRenderer }
export { JsonRenderSpec }
export { PartialWithoutId }
export { RemoteConnectionInfo }
export { RemoteDockOptions }
export { RpcBroadcastOptions }
export { RpcFunctionAgentOptions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { Thenable }
// #endregion