/**
 * Generated by tsnapi — public API snapshot of `devframe/node`
 */
// #region Interfaces
export interface CreateH3DevToolsHostOptions {
  app?: unknown;
  origin: string;
  mount?: (_: string, _: string) => void | Promise<void>;
  appName: string;
  workspaceRoot?: string;
}
export interface CreateHostContextOptions {
  cwd: string;
  workspaceRoot?: string;
  mode: 'dev' | 'build';
  host: DevToolsHost;
  builtinRpcDeclarations?: readonly RpcFunctionDefinitionAny[];
}
export interface CreateStorageOptions<T extends object> {
  filepath: string;
  initialValue: T;
  mergeInitialValue?: false | ((_: T, _: T) => T);
  debounce?: number;
}
export interface StaticRpcDumpCollection {
  manifest: StaticRpcDumpManifest;
  files: Record<string, StaticRpcDumpFile>;
}
export interface StaticRpcDumpFile {
  serialization: StaticRpcDumpSerialization;
  fnName: string;
  data: unknown;
}
export interface StaticRpcDumpManifestQueryEntry {
  type: 'query';
  records: Record<string, string>;
  fallback?: string;
  serialization?: StaticRpcDumpSerialization;
}
export interface StaticRpcDumpManifestStaticEntry {
  type: 'static';
  path: string;
  serialization?: StaticRpcDumpSerialization;
}
// #endregion

// #region Types
export type StaticRpcDumpManifest = Record<string, StaticRpcDumpManifestValue>;
export type StaticRpcDumpManifestValue = StaticRpcDumpManifestStaticEntry | StaticRpcDumpManifestQueryEntry | any;
export type StaticRpcDumpSerialization = 'json' | 'structured-clone';
// #endregion

// #region Classes
export declare class DevToolsAgentHost implements DevToolsAgentHost$1 {
  readonly context: DevToolsNodeContext;
  readonly events: EventEmitter<DevToolsAgentHostEvents>;
  private readonly tools;
  private readonly resources;
  private _rpcUnsubscribe;
  constructor(_: DevToolsNodeContext);
  registerTool(_: AgentToolInput): AgentHandle;
  unregisterTool(_: string): boolean;
  registerResource(_: AgentResourceInput): AgentHandle;
  unregisterResource(_: string): boolean;
  list(): AgentManifest;
  getTool(_: string): AgentTool | undefined;
  getResource(_: string): AgentResource | undefined;
  invoke(_: string, _: unknown): Promise<unknown>;
  read(_: string): Promise<AgentResourceContent>;
  _dispose(): void;
  private _validateToolId;
  private _projectTool;
  private _collectRpcTools;
  private _findRpcDefinition;
  private _coercePositionalArgs;
}
export declare class DevToolsDiagnosticsHost implements DevToolsDiagnosticsHost$1 {
  readonly context: DevToolsNodeContext;
  private _definitions;
  private _logger;
  readonly defineDiagnostics: typeof defineDiagnostics;
  readonly createLogger: typeof createLogger;
  constructor(_: DevToolsNodeContext, _?: unknown[]);
  get logger(): DevToolsDiagnosticsLogger;
  register(_: unknown): void;
  private _rebuild;
}
export declare class DevToolsViewHost implements DevToolsViewHost$1 {
  readonly context: DevToolsNodeContext;
  buildStaticDirs: {
    baseUrl: string;
    distDir: string;
  }[];
  constructor(_: DevToolsNodeContext);
  hostStatic(_: string, _: string): void;
}
export declare class RpcFunctionsHost extends RpcFunctionsCollectorBase<DevToolsRpcServerFunctions, DevToolsNodeContext> implements RpcFunctionsHost$1 {
  _rpcGroup: BirpcGroup<DevToolsRpcClientFunctions, DevToolsRpcServerFunctions, false>;
  _asyncStorage: AsyncLocalStorage<DevToolsNodeRpcSession>;
  constructor(_: DevToolsNodeContext);
  sharedState: RpcSharedStateHost;
  streaming: RpcStreamingHost;
  _emitSessionDisconnected(_: DevToolsNodeRpcSessionMeta): void;
  invokeLocal<T extends keyof DevToolsRpcServerFunctions, Args extends Parameters<DevToolsRpcServerFunctions[T]>>(_: T, ..._: Args): Promise<Awaited<ReturnType<DevToolsRpcServerFunctions[T]>>>;
  broadcast<T extends keyof DevToolsRpcClientFunctions, Args extends Parameters<DevToolsRpcClientFunctions[T]>>(_: RpcBroadcastOptions<T, Args>): Promise<void>;
  getCurrentRpcSession(): DevToolsNodeRpcSession | undefined;
}
// #endregion

// #region Functions
export declare function collectStaticRpcDump(_: Iterable<RpcFunctionDefinitionAny>, _: any): Promise<StaticRpcDumpCollection>;
export declare function createH3DevToolsHost(_: CreateH3DevToolsHostOptions): DevToolsHost;
export declare function createHostContext(_: CreateHostContextOptions): Promise<DevToolsNodeContext>;
export declare function createRpcSharedStateServerHost(_: RpcFunctionsHost$1): RpcSharedStateHost;
export declare function createRpcStreamingServerHost(_: RpcFunctionsHost$1): RpcStreamingHost;
export declare function createStorage<T extends object>(_: CreateStorageOptions<T>): SharedState<T>;
export declare function isObject(_: unknown): value is Record<string, any>;
export declare function normalizeHttpServerUrl(_: string, _: number | string): string;
// #endregion

// #region Other
export { StartedServer }
export { startHttpAndWs }
export { StartHttpAndWsOptions }
// #endregion