/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/cli-commands`
 */
// #region Interfaces
export interface BuildOptions {
  root: string;
  config?: string;
  outDir: string;
  base: string;
}
export interface StartOptions {
  root?: string;
  config?: string;
  host: string;
  port?: string | number;
  open?: boolean;
}
// #endregion

// #region Functions
export declare function build(_: BuildOptions): Promise<void>;
export declare function start(_: StartOptions): Promise<void>;
// #endregion