/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/config`
 */
// #region Other
export { DevToolsApply }
export { DevToolsConfig }
export { isDevToolsEnabled }
export { normalizeDevToolsConfig }
export { ResolvedDevToolsConfig }
// #endregion