/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/config`
 */
// #region Interfaces
export interface DevToolsConfig extends Partial<StartOptions> {
  enabled: boolean;
  clientAuth?: boolean;
  clientAuthTokens?: string[];
}
export interface ResolvedDevToolsConfig {
  config: Omit<DevToolsConfig, 'enabled'> & {
    host: string;
  };
  enabled: boolean;
}
// #endregion

// #region Functions
export declare function normalizeDevToolsConfig(_: DevToolsConfig | boolean | undefined, _: string): ResolvedDevToolsConfig;
// #endregion