/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/dirs`
 */
// #region Variables
export declare const dirClientStandalone: string;
export declare const dirDist: string;
// #endregion