/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/dirs`
 */
// #region Variables
export declare const DEVTOOLS_ASSETS_BASE: string;
export declare const dirAssets: string;
export declare const dirDist: string;
// #endregion