/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools`
 */
// #region Types
export type BuiltinServerFunctions = RpcDefinitionsToFunctions<typeof builtinRpcDeclarations>;
// #endregion

// #region Functions
export declare function createDevToolsContext(_: ResolvedConfig, _?: ViteDevServer): Promise<DevToolsNodeContext>;
export declare function createDevToolsMiddleware(_: CreateWsServerOptions): Promise<{
  h3: _$h3.App;
  rpc: _$birpc.BirpcGroup<_$devframe.DevToolsRpcClientFunctions, _$devframe.DevToolsRpcServerFunctions, false>;
  middleware: _$h3.NodeListener;
  getConnectionMeta: () => Promise<_$devframe.ConnectionMeta>;
}>;
export declare function DevTools(_?: DevToolsOptions): Promise<Plugin[]>;
// #endregion

// #region Other
export { DevToolsInternalContext }
export { InternalAnonymousAuthStorage }
// #endregion