/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools`
 */
// #region Interfaces
export interface CreateDevToolsHubOptions {
  context: ViteDevToolsNodeContext;
  renderers?: readonly DockRendererRegistration[];
  ui?: ViteDevToolsUiOptions;
  server?: Server;
  host?: string;
  wsPort?: number;
}
export interface DevToolsHub {
  hub: HubInstance;
  middleware: HubInstance['nodeMiddleware'];
  getConnectionMeta: () => ConnectionMeta;
  close: () => Promise<void>;
}
// #endregion

// #region Types
export type BuiltinServerFunctions = RpcDefinitionsToFunctions<typeof builtinRpcDeclarations>;
// #endregion

// #region Functions
export declare function createDevToolsContext(_: ResolvedConfig, _?: ViteDevServer): Promise<ViteDevToolsNodeContext>;
export declare function createDevToolsHub(_: CreateDevToolsHubOptions): Promise<DevToolsHub>;
export declare function DevTools(_?: DevToolsOptions): Promise<Plugin[]>;
// #endregion

// #region Referenced (internal)
interface DevToolsOptions {
  cwd?: string;
  builtinDevTools?: boolean;
  renderers?: readonly DockRendererRegistration[];
  branding?: ViteDevToolsUiOptions['branding'];
  embeddedVisibility?: ViteDevToolsUiOptions['embeddedVisibility'];
  dockPreferences?: ViteDevToolsUiOptions['dockPreferences'];
  build?: {
    withApp?: boolean;
    outDir?: string;
  };
}
interface ViteDevToolsUiOptions {
  branding?: DevframeBranding;
  embeddedVisibility?: EmbeddedVisibility;
  dockPreferences?: DevframeDockPreferences;
}
// #endregion

// #region Other
export { DevToolsInternalContext }
export { InternalAnonymousAuthStorage }
// #endregion