/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/integration`
 */
// #region Interfaces
export interface DevToolsIntegrationOptions {
  config: ResolvedConfig;
}
// #endregion

// #region Functions
export declare function DevToolsIntegration(_: DevToolsIntegrationOptions): Plugin;
export declare function runDevTools(_: unknown): Promise<void>;
// #endregion