/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/integration`
 */
// #region Interfaces
export interface DevToolsIntegrationConfig {
  host: string;
  options: boolean | DevToolsConfig | undefined;
}
export interface DevToolsIntegrationOptions {
  config: unknown;
  devtools: DevToolsIntegrationConfig;
}
// #endregion

// #region Functions
export declare function DevToolsIntegration(_: DevToolsIntegrationOptions): Promise<{
  name: string;
}[]>;
export declare function runDevTools(_: unknown, _: DevToolsIntegrationConfig): Promise<void>;
// #endregion