/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/internal`
 */
// #region Other
export { DevToolsInternalContext }
export { getInternalContext }
export { InternalAnonymousAuthStorage }
// #endregion