/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/integration`
 */
// #region Interfaces
export interface DevToolsIntegrationOptions {
  config: unknown;
}
// #endregion

// #region Functions
export declare function DevToolsIntegration(_: DevToolsIntegrationOptions): {
  name: string;
};
export declare function runDevTools(_: unknown): Promise<void>;
// #endregion