/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/utils/human-id`
 */
// #region Functions
export declare function humanId(_?: Options | string | boolean): string;
// #endregion