/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-kit/utils/when`
 */
// #region Other
export { evaluateWhen }
export { resolveContextValue }
export { WhenContext }
export { WhenExpression }
// #endregion