/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-vite-task`
 */
// #region Functions
export declare function DevToolsViteTaskUI(): PluginWithDevTools;
// #endregion

// #region Variables
export declare const VITE_TASK_DEVTOOLS_BASE: string;
// #endregion