/**
 * Generated by tsnapi — public API snapshot of `devframe/helpers/nuxt`
 */
// #region Interfaces
export interface DevframeNuxtModuleOptions {
  baseURL?: string;
  skipAppDefaults?: boolean;
}
// #endregion

// #region Default Export
declare const _default: _$_nuxt_schema0.NuxtModule<DevframeNuxtModuleOptions, DevframeNuxtModuleOptions, false>;
export default _default
// #endregion