export type { WhenContext } from '../utils/when'

export * from './vite-augment'
export * from './vite-plugin'
export type { RpcDefinitionsFilter, RpcDefinitionsToFunctions } from 'takubox/rpc'

// NOTE: we re-export takubox's types individually rather than using
// `export * from 'takubox/types'` because the rolldown-plugin-dts step
// fails with a `MemberExpression` AST error on namespace re-exports
// from external packages (tsdown 0.21 / rolldown-plugin-dts 0.23).
// Revisit once upstream supports it.
export type {
  ClientScriptEntry,
  ConnectionMeta,
  DevToolsCapabilities,
  DevToolsChildProcessExecuteOptions,
  DevToolsChildProcessTerminalSession,
  DevToolsClientCommand,
  DevToolsCommandBase,
  DevToolsCommandEntry,
  DevToolsCommandHandle,
  DevToolsCommandKeybinding,
  DevToolsCommandShortcutOverrides,
  DevToolsCommandsHost,
  DevToolsCommandsHostEvents,
  DevToolsDockEntriesGrouped,
  DevToolsDockEntry,
  DevToolsDockEntryBase,
  DevToolsDockEntryCategory,
  DevToolsDockEntryIcon,
  DevToolsDockHost,
  DevToolsDocksUserSettings,
  DevToolsDockUserEntry,
  DevToolsHost,
  DevToolsLogElementPosition,
  DevToolsLogEntry,
  DevToolsLogEntryFrom,
  DevToolsLogEntryInput,
  DevToolsLogFilePosition,
  DevToolsLogHandle,
  DevToolsLogLevel,
  DevToolsLogsClient,
  DevToolsLogsHost,
  DevToolsNodeRpcSession,
  DevToolsNodeUtils,
  DevToolsRpcClientFunctions,
  DevToolsRpcServerFunctions,
  DevToolsRpcSharedStates,
  DevToolsServerCommandEntry,
  DevToolsServerCommandInput,
  DevToolsTerminalHost,
  DevToolsTerminalSession,
  DevToolsTerminalSessionBase,
  DevToolsTerminalSessionStreamChunkEvent,
  DevToolsTerminalStatus,
  DevToolsViewAction,
  DevToolsViewBuiltin,
  DevToolsViewCustomRender,
  DevToolsViewHost,
  DevToolsViewIframe,
  DevToolsViewJsonRender,
  DevToolsViewLauncher,
  DevToolsViewLauncherStatus,
  EntriesToObject,
  EventEmitter,
  EventsMap,
  EventUnsubscribe,
  JsonRenderElement,
  JsonRenderer,
  JsonRenderSpec,
  PartialWithoutId,
  RemoteConnectionInfo,
  RemoteDockOptions,
  RpcBroadcastOptions,
  RpcFunctionsHost,
  RpcSharedStateGetOptions,
  RpcSharedStateHost,
  Thenable,
} from 'takubox/types'
