/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/client/webcomponents`
 */
// #region Interfaces
export interface BadgeProps {
  text?: string;
  variant?: 'default' | 'info' | 'success' | 'warning' | 'danger';
  title?: string;
  minWidth?: number;
}
export interface ButtonProps {
  label?: string;
  variant?: BaseVariant;
  icon?: string;
  disabled?: boolean;
}
export interface CodeBlockProps {
  code?: string;
  filename?: string;
  language?: string;
  height?: number;
}
export interface DataTableColumn {
  key: string;
  label?: string;
  width?: string;
}
export interface DataTableProps {
  columns?: (string | DataTableColumn)[];
  rows?: Record<string, unknown>[];
  height?: number;
}
export interface DividerProps {
  label?: string;
}
export interface IconProps {
  name?: string;
  size?: number;
}
export interface JsonRenderElement<T extends string = string, P = Record<string, unknown>> {
  type: T;
  props: P;
  children?: string[];
  visible?: VisibilityCondition;
  on?: Record<string, ActionBinding | ActionBinding[]>;
  repeat?: {
    statePath: string;
    key?: string;
  };
  watch?: Record<string, ActionBinding | ActionBinding[]>;
}
export interface KeyValueTableProps {
  data?: Record<string, unknown>;
}
export interface ProgressProps {
  value: number;
  max?: number;
  label?: string;
}
export interface SwitchProps {
  value?: boolean;
  label?: string;
  disabled?: boolean;
}
export interface TabDescriptor {
  value: string;
  label: string;
  icon?: string;
  badge?: string;
  badgeVariant?: 'default' | 'info' | 'success' | 'warning' | 'danger';
}
export interface TabsProps {
  tabs: TabDescriptor[];
  value?: string;
  defaultValue?: string;
  orientation?: 'horizontal' | 'vertical';
}
export interface TextInputProps {
  value?: string;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
}
export interface TextProps {
  text?: string;
  variant?: 'heading' | 'subheading' | 'body' | 'caption' | 'code';
  weight?: 'normal' | 'medium' | 'bold';
}
export interface TreeProps {
  data?: unknown;
  defaultExpanded?: boolean;
}
// #endregion

// #region Functions
export declare function createDockEntryState(_: DevToolsDockEntry, _: Ref<DevToolsDockEntry | null>): DockEntryState;
export declare function DEFAULT_DOCK_PANEL_STORE(): DockPanelStorage;
export declare function sharedStateToRef<T>(_: SharedState<T>): ShallowRef<T>;
export declare function useDocksEntries(_: DevToolsRpcClient): Promise<Ref<DevToolsDockEntry[]>>;
// #endregion

// #region Variables
export declare const DockEmbedded: VueElementConstructor<{
  context: DocksContext;
}>;
export declare const DockStandalone: VueElementConstructor<{
  context: DocksContext;
}>;
// #endregion