/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools/client/webcomponents`
 */
// #region Interfaces
export interface CardProps {
  title?: string;
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  variant?: CardVariant;
  interactive?: boolean;
}
export interface JsonRenderElement<T extends string = string, P = Record<string, unknown>> {
  type: T;
  props: P;
  children?: string[];
  visible?: VisibilityCondition;
  on?: Record<string, ActionBinding | ActionBinding[]>;
  repeat?: {
    statePath: string;
    key?: string;
  };
  watch?: Record<string, ActionBinding | ActionBinding[]>;
}
// #endregion

// #region Functions
export declare function createDockEntryState(_: DevToolsDockEntry, _: Ref<DevToolsDockEntry | null>): DockEntryState;
export declare function DEFAULT_DOCK_PANEL_STORE(): DockPanelStorage;
export declare function sharedStateToRef<T>(_: SharedState<T>): ShallowRef<T>;
export declare function useDocksEntries(_: DevToolsRpcClient): Promise<Ref<DevToolsDockEntry[]>>;
// #endregion

// #region Variables
export declare const DockEmbedded: VueElementConstructor<{
  context: DocksContext;
}>;
export declare const DockStandalone: VueElementConstructor<{
  context: DocksContext;
}>;
// #endregion