/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/cli`
 */
// #region Interfaces
export interface CliHandle {
  parse: (_?: string[]) => Promise<void>;
}
export interface CreateCliOptions {
  defaultPort?: number;
}
// #endregion

// #region Functions
export declare function createCli(_: DevtoolDefinition, _?: CreateCliOptions): CliHandle;
// #endregion