/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/embedded`
 */
// #region Interfaces
export interface CreateEmbeddedOptions {
  ctx: DevToolsNodeContext;
}
// #endregion

// #region Functions
export declare function createEmbedded(_: DevtoolDefinition, _: CreateEmbeddedOptions): Promise<void>;
// #endregion