/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/kit`
 */
// #region Interfaces
export interface KitPlugin {
  name: string;
  devtools: {
    setup: DevtoolDefinition['setup'];
    capabilities?: DevtoolDefinition['capabilities'];
  };
}
// #endregion

// #region Functions
export declare function toKitPlugin(_: DevtoolDefinition): KitPlugin;
// #endregion