/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/mcp`
 */
// #region Interfaces
export interface CreateMcpServerOptions {
  transport?: 'stdio';
  exposeSharedState?: boolean | ((_: string) => boolean);
  serverName?: string;
  serverVersion?: string;
  onReady?: (_: {
    transport: 'stdio';
  }) => void;
}
export interface McpServerHandle {
  stop: () => Promise<void>;
}
// #endregion

// #region Functions
export declare function createMcpServer(_: DevtoolDefinition, _?: CreateMcpServerOptions): Promise<McpServerHandle>;
// #endregion