/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/spa`
 */
// #region Interfaces
export interface CreateSpaOptions {
  outDir?: string;
  base?: string;
}
// #endregion

// #region Functions
export declare function createSpa(_: DevtoolDefinition, _?: CreateSpaOptions): Promise<void>;
// #endregion