/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/vite`
 */
// #region Interfaces
export interface DevframeVitePlugin {
  name: string;
  apply: 'serve';
  configureServer: (_: {
    middlewares: {
      use: (_: string, _: any) => void;
    };
  }) => void;
}
export interface DevframeVitePluginOptions {
  base?: string;
}
// #endregion

// #region Functions
export declare function devframeVite(_: DevtoolDefinition, _?: DevframeVitePluginOptions): DevframeVitePlugin;
// #endregion