/**
 * Generated by tsnapi — public API snapshot of `@vitejs/devtools-rolldown/node`
 */
// #region Classes
export declare class RolldownEventsReader {
  readonly filepath: string;
  private readonly cacheKey;
  lastBytes: number;
  lastTimestamp: number;
  manager: RolldownEventsManager;
  meta: SessionMeta | undefined;
  private pendingRead;
  private pendingSummaryRead;
  private lineNumber;
  private moduleEventIndex;
  private stringRefIndex;
  private pendingHookCallStarts;
  private moduleMetricsCache;
  private moduleMetricsCacheBytes;
  private pendingModuleMetrics;
  private assetsReadyLocations;
  private assetsHydrated;
  private pendingPackageSummaryRead;
  private packageSummaryTimestamp;
  private summaryOnly;
  private packageSummaryOnly;
  private metricsSummaryOnly;
  private logCache;
  private constructor();
  static get(_: string, _?: string): RolldownEventsReader;
  static peek(_: string, _?: string): RolldownEventsReader | undefined;
  read(): Promise<void>;
  readSummary(): Promise<void>;
  private readChanges;
  private readSummaryChanges;
  private readEventLines;
  readAssets(): Promise<void>;
  private recordAssetsReadyLocation;
  readPackageSummary(): Promise<void>;
  readPluginBuildMetricsSummary(): Promise<Map<number, PluginBuildMetricsSummary>>;
  ensurePackageSummaryCache(): Promise<void>;
  private readPackageSummaryChanges;
  private recordPackageSummarySkippedLine;
  private recordPackageTransformEnd;
  private recordPackageTransformSize;
  private getModuleEventIndex;
  private indexEvent;
  private readEventsAt;
  private readStringRefs;
  readModuleBuildMetrics(_: string): Promise<ModuleBuildMetrics>;
  hydratePluginBuildMetrics(_: number): Promise<void>;
  private clearModuleMetricsCache;
  private setCachedModuleBuildMetrics;
  private readIndexedHookEvents;
  private hydrateModuleBuildMetricsFromIndex;
  private hydratePluginBuildMetricsFromIndex;
  private hydrateModuleBuildMetrics;
  hasPendingRead(): boolean;
  hasReadData(): boolean;
  private createLogCacheState;
  hasCompleteSession(): boolean;
  isReadingCompleteSession(): boolean;
  dispose(): void;
  private resetReadState;
  private disposeData;
  [Symbol.dispose](): void;
}
// #endregion

// #region Functions
export declare function createSessionCompareDetails(_: RolldownEventsReader, _: RolldownEventsReader): Promise<SessionCompareDetails>;
export declare function getLogsManager(_: ViteDevToolsNodeContext): RolldownLogsManager;
export declare function getPackageMeta(_: RolldownEventsReader): PackageMeta;
// #endregion

// #region Referenced (internal)
interface ModuleBuildMetrics {
  resolve_ids: RolldownResolveInfo[];
  loads: RolldownModuleLoadInfo[];
  transforms: Array<Omit<RolldownModuleTransformInfo, 'diff_added' | 'diff_removed'> & {
    source_code_size: number;
    transformed_code_size: number;
  }>;
}
interface PackageMeta {
  isSupported: boolean;
  packages: PackageInfo$1[];
}
interface PluginBuildMetricsSummary {
  plugin_id: number;
  plugin_name: string;
  total: PluginMetricSummary;
  resolve: PluginMetricSummary;
  load: PluginMetricSummary;
  transform: PluginMetricSummary;
}
declare class RolldownEventsManager {
  eventCount: number;
  lastEvent: RolldownEvent | undefined;
  chunks: Map<number, RolldownChunkInfo>;
  assets: Map<string, RolldownAssetInfo>;
  chunkAssetMap: Map<number, RolldownAssetInfo>;
  modules: Map<string, Module & {
    build_metrics?: ModuleBuildMetrics;
  }>;
  packageGraphReady: boolean;
  packages: Map<string, PackageInfo>;
  source_refs: Map<string, ContentInfo>;
  module_build_hook_events: Map<string, PendingModuleBuildHookEvent>;
  module_build_metrics: Map<string, ModuleBuildMetrics>;
  plugin_build_metrics: Map<number, PluginBuildMetrics>;
  build_start_time: number;
  build_end_time: number;
  getEventContentInfo(_: any, _: 'content'): ContentInfo;
  recordBuildMetrics(_: ModuleBuildHookEvents): void;
  handleEvent(_: Event): ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").SessionMeta & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookTransformCallStart & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookTransformCallEnd & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookLoadCallStart & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookLoadCallEnd & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").BuildStart & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").BuildEnd & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookResolveIdCallStart & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & HookResolveIdCallEnd & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").ModuleGraphReady & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").HookRenderChunkStart & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").HookRenderChunkEnd & {
    event_id: string;
  }) | ({
    timestamp: string;
    session_id: string;
  } & import("@rolldown/debug").AssetsReady & {
    event_id: string;
  }) | undefined;
  dispose(): void;
  snapshot(): RolldownEventsManagerSnapshot;
  restore(_: RolldownEventsManagerSnapshot): void;
  [Symbol.dispose](): void;
}
declare class RolldownLogsManager {
  readonly dir: string;
  constructor(_: string);
  private get aliasesPath();
  readAliases(): Promise<Record<string, string>>;
  private writeAliases;
  list(): Promise<BuildInfo[]>;
  renameSession(_: string, _: string): Promise<string>;
  deleteSession(_: string): Promise<void>;
  loadSession(_: string): Promise<RolldownEventsReader>;
  loadSessionSummary(_: string): Promise<RolldownEventsReader>;
  loadAssetSession(_: string): Promise<RolldownEventsReader>;
  loadPackageSession(_: string): Promise<RolldownEventsReader>;
}
interface SessionCompareDetails {
  sessionStats: {
    previous: {
      packages: number;
      duplicatedPackages: number;
    };
    current: {
      packages: number;
      duplicatedPackages: number;
    };
  };
  assets: SessionCompareAssetDiff[];
  chunks: SessionCompareChunkDiff[];
  packages: SessionComparePackageDiff[];
  plugins: SessionComparePluginDiff[];
}
// #endregion