import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'rpc/index': 'src/rpc/index.ts',
    'rpc/client': 'src/rpc/client.ts',
    'rpc/server': 'src/rpc/server.ts',
    'rpc/transports/ws-client': 'src/rpc/transports/ws-client.ts',
    'rpc/transports/ws-server': 'src/rpc/transports/ws-server.ts',
    'types/index': 'src/types/index.ts',
    'node/index': 'src/node/index.ts',
    'node/auth': 'src/node/auth/index.ts',
    'node/internal': 'src/node/internal/index.ts',
    'constants': 'src/constants.ts',
    'utils/colors': 'src/utils/colors.ts',
    'utils/events': 'src/utils/events.ts',
    'utils/hash': 'src/utils/hash.ts',
    'utils/human-id': 'src/utils/human-id.ts',
    'utils/launch-editor': 'src/utils/launch-editor.ts',
    'utils/nanoid': 'src/utils/nanoid.ts',
    'utils/open': 'src/utils/open.ts',
    'utils/promise': 'src/utils/promise.ts',
    'utils/serve-static': 'src/utils/serve-static.ts',
    'utils/shared-state': 'src/utils/shared-state.ts',
    'utils/streaming-channel': 'src/utils/streaming-channel.ts',
    'utils/structured-clone': 'src/utils/structured-clone.ts',
    'utils/when': 'src/utils/when.ts',
    'adapters/cli': 'src/adapters/cli.ts',
    'adapters/dev': 'src/adapters/dev.ts',
    'adapters/build': 'src/adapters/build.ts',
    'adapters/vite': 'src/adapters/vite.ts',
    'adapters/embedded': 'src/adapters/embedded.ts',
    'adapters/mcp': 'src/adapters/mcp.ts',
    'client/index': 'src/client/index.ts',
    'recipes/open-helpers': 'src/recipes/open-helpers.ts',
  },
  tsconfig: '../../../tsconfig.base.json',
  clean: true,
  dts: true,
  exports: true,
  // Keep transitive external type graphs out of dts bundling.
  // `vite`/`esbuild`/`postcss` are pulled in via the kit client's
  // `declare module 'vite'` augmentation and contain
  // rolldown-incompatible re-exports that would otherwise fail dts
  // generation with dozens of MISSING_EXPORT errors.
  deps: {
    neverBundle: [
      'vite',
      'esbuild',
      'postcss',
      'rolldown',
      /^@rolldown\//,
      /^@oxc-project\//,
      'terser',
      '@jridgewell/trace-mapping',
    ],
    onlyBundle: [
      'acorn',
      'ansis',
      'bundle-name',
      'default-browser',
      'default-browser-id',
      'define-lazy-prop',
      'get-port-please',
      'human-id',
      'immer',
      'is-docker',
      'is-in-ssh',
      'is-inside-container',
      'is-wsl',
      'launch-editor',
      'mlly',
      'obug',
      'ohash',
      'open',
      'p-limit',
      'perfect-debounce',
      'picocolors',
      'powershell-utils',
      'run-applescript',
      'shell-quote',
      'structured-clone-es',
      'tinyexec',
      'ua-parser-modern',
      'whenexpr',
      'wsl-utils',
      'yocto-queue',
    ],
  },
})
